### ISSUE TITLE
Centroid dashboard links

### ISSUE THREAD

**Issue by taldcroft** [sot/aca_weekly_report#2]
It looks like the links from the ACA weekly status are wrong.  E.g.

  https://icxc.cfa.harvard.edu/aspect/dashboard_reports/23/23341/

I think it should be `centroid_dashboard`.

And I can't remember if we discussed, but could the centroid_dashboard pages be on the cxc server so not require VPN?

**Comment by jeanconn** [comment]
I didn't have permission to write into the old/current area so did the testing in mica and set up the most recent references to a new dir.  Which isn't *quite* finished because the PR that we are about to call version 0.1.0 was still a play area.

**Comment by jeanconn** [comment]
The current report links are working with the current mica centroid  outputs.
